name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions: {}
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Check ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'macos-26'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
          cache: false
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - name: install cppcheck
        if: runner.os == 'Linux'
        run: sudo apt-get install --yes cppcheck
      - name: install cppcheck
        if: runner.os == 'macOS'
        run: brew install cppcheck
      - name: check
        run: 'just check'
