name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions: {}
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: Check macos-26
    permissions:
      contents: read
    runs-on: macos-26
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - name: install cppcheck
        run: brew install cppcheck
      - name: check
        run: 'just check'
