name: DCO
on:
  pull_request:
permissions: {}
concurrency:
  group: dco-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dco:
    name: DCO
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-dco.yml@2050692900f7dcd883e416ebee37a1b97b119203 # v0.3.0
